In [ ]:
# ==========================================================
# Importação da biblioteca Pandas responsável pela leitura, manipulação e análise dos dados.
# ==========================================================

import pandas as pd

# ==========================================================
# Leitura dos arquivos CSV exportados dos dois ambientes FAC.
# Cada arquivo representa a lista de usuários de um ambiente.
# ==========================================================

ctc = pd.read_csv("CTC_users.csv")
dtc = pd.read_csv("DTC_users.csv")


# ==========================================================
# Exibe as primeiras linhas de cada arquivo para validar se a importação foi realizada corretamente.
# ==========================================================

display(ctc.head())
display(dtc.head())

,# username,display name,first name,last name,email,alternate emails,phone number,mobile number,street address,city,...,department,title,birthdate,custom1,custom2,custom3,password,otp,otp-only,groups
0,alecsandro.melo,alecsandro.melo,Alecsandro,Melo,alecsandro.melo@mamtech.com.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$F8C2B8784DEC207B3DC28B4154B18CAC48F1C4F...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
1,alex.gomes,alex.gomes,Alex,Gomes,alex.gomes@sencinet.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$B5B634473449AD8D5BCA54B796A06C6F48F3A2C...,NaN,f,OI_GRP HP MONITOR;SENCI_GRP CISCO ADMIN;SENCI_...
2,ana.osorio,ana.osorio,Ana,Osorio,ana.osorio@oi.net.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$E0958E54CCF5575766438AE2E2DFE05CB1F7EBD...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
3,ana.trindade,ana.trindade,Ana,Trindade,ana.trindade@mamtech.com.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$3217508F460E4C769E743238E3893ADEAF4C89A...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
4,anabelly.ferreira,anabelly.ferreira,Anabelly,Ferreira,anabelly.ferreira@oi.net.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$18EF2AD04F1981E5DA57A3D4A96DD3FA2111123...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...

,# username,display name,first name,last name,email,alternate emails,phone number,mobile number,street address,city,...,department,title,birthdate,custom1,custom2,custom3,password,otp,otp-only,groups
0,alecsandro.melo,alecsandro.melo,Alecsandro,Melo,alecsandro.melo@mamtech.com.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$879EF3D61AEAF0181EF570A89E1DDB4B179852E...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
1,alex.gomes,alex.gomes,Alex,Gomes,alex.gomes@sencinet.com,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$AD9FF97034160EE1131F37229402E9CA0821C72...,NaN,f,OI_GRP HP MONITOR;SENCI_GRP CISCO ADMIN;SENCI_...
2,ana.osorio,ana.osorio,Ana,Osorio,ana.osorio@oi.net.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$4564709F3CC738129E6E8B4FA886830FA45550E...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
3,ana.trindade,ana.trindade,Ana,Trindade,ana.trindade@mamtech.com.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$4FD6E8182418F7BAA61740E90868FB5FB702651...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...
4,anabelly.ferreira,anabelly.ferreira,Anabelly,Ferreira,anabelly.ferreira@oi.net.br,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,AES256$F8D138717DBA6A89C3866C2FD7313898DFCCDB1...,NaN,f,OI_GRP HP ADMIN;SENCI_OI ACCESS_GRP CISCO ADMI...

In [ ]:
# ==========================================================
# Exibe a quantidade total de registros (usuários) encontrados em cada ambiente.
# ==========================================================

print("Quantidade de usuários no CTC:", len(ctc))
print("Quantidade de usuários no DTC:", len(dtc))

Quantidade de usuários no CTC: 95
Quantidade de usuários no DTC: 106

In [ ]:
# ==========================================================
# Exibe o nome das colunas presentes em cada arquivo.
# Esta etapa foi utilizada para identificar o nome correto da coluna que contém o login dos usuários.
# ==========================================================

ctc.columns
dtc.columns

Index(['# username', 'display name', 'first name', 'last name', 'email',
       'alternate emails', 'phone number', 'mobile number', 'street address',
       'city', 'state/province', 'zip/postal code', 'country', 'company',
       'department', 'title', 'birthdate', 'custom1', 'custom2', 'custom3',
       'password', 'otp', 'otp-only', 'groups'],
      dtype='str')

In [ ]:
# ==========================================================
# Cria um conjunto (set) contendo apenas os usernames.
#
# O uso de "set" elimina possíveis usuários duplicados e permite realizar comparações de forma muito mais rápida.
# ==========================================================

usuarios_ctc = set(ctc["# username"])
usuarios_dtc = set(dtc["# username"])

# ==========================================================
# Exibe a quantidade total de usuários únicos encontrados em cada ambiente.
# ==========================================================

print("Total CTC:", len(usuarios_ctc))
print("Total DTC:", len(usuarios_dtc))

Total CTC: 95
Total DTC: 106

In [31]:
# ==========================================================
# Identifica usuários existentes no ambiente CTC, mas ausentes no ambiente DTC.
#
# A operação de diferença entre conjuntos retorna apenas os elementos exclusivos do primeiro conjunto.
# ==========================================================

somente_ctc = usuarios_ctc - usuarios_dtc

somente_ctc

{'francisco.ribeiro',
 'jackeline.carmo',
 'joao.cezar.external',
 'rafael.vieira',
 'thiago.sousa'}

In [32]:
# ==========================================================
# Identifica usuários existentes no ambiente DTC, mas ausentes no ambiente CTC.
# ==========================================================

somente_dtc = usuarios_dtc - usuarios_ctc

somente_dtc

{'anisio.santos',
 'caio.padilha',
 'davi.carmo',
 'felipe.santos',
 'jesus.araujo',
 'lucas.freitas',
 'luciano.oliveira',
 'marcos.vinicius',
 'mateus.jesus.mam',
 'max.oliveira',
 'rafael.pereira',
 'sarli.silva',
 'sidney.neiva',
 'tiago.carvalho',
 'wesley.prado',
 'wilton.pereira'}

In [33]:
# ==========================================================
# Exibe a quantidade de divergências encontradas em cada ambiente.
# ==========================================================

print("Usuários somente no CTC:", len(somente_ctc))
print("Usuários somente no DTC:", len(somente_dtc))

Usuários somente no CTC: 5
Usuários somente no DTC: 16

In [41]:
# ==========================================================
# Cria uma lista vazia que será utilizada para montar o relatório final contendo todas as divergências.
# ==========================================================

divergencias = []

# ==========================================================
# Percorre todos os usuários encontrados apenas no CTC e adiciona essas informações na lista do relatório.
# ==========================================================

for usuario in somente_ctc:

    divergencias.append({

        "Usuario": usuario,

        "Origem": "CTC",

        "Situacao": "Existe no CTC, mas não existe no DTC"

    })


# ==========================================================
# Percorre todos os usuários encontrados apenas no DTC e adiciona essas informações na lista do relatório.
# ==========================================================

for usuario in somente_dtc:

    divergencias.append({

        "Usuario": usuario,

        "Origem": "DTC",

        "Situacao": "Existe no DTC, mas não existe no CTC"

    })


# ==========================================================
# Converte a lista de dicionários em um DataFrame.
#
# O DataFrame facilita a visualização dos dados e também permite exportá-los para outros formatos.
# ==========================================================

df_divergencias = pd.DataFrame(divergencias)

df_divergencias


# ==========================================================
# Exporta o relatório final para um arquivo Excel.
#
# O parâmetro index=False impede que o índice numérico seja gravado como uma coluna no arquivo.
# ==========================================================

df_divergencias.to_excel("Relatorio_Divergencias_FAC.xlsx",

    index=False

)